name: vibin_app
description: "Cross-platform app for the self-hosted music streaming server Vibin'"

publish_to: 'none'

version: 0.0.1-beta.1+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8

  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

  retrofit: ^4.6.0
  logger: ^2.6.0
  json_annotation: ^4.9.0
  dio: ^5.9.0
  get_it: ^8.2.0
  go_router: ^16.2.1
  provider: ^6.1.5+1
  package_info_plus: ^9.0.0
  intl: any

  just_audio: ^0.10.5
  audio_service: ^0.18.18
  just_audio_media_kit: ^2.1.0

  media_kit_libs_linux: any
  media_kit_libs_windows_audio: any
  media_kit_libs_android_audio: any
  media_kit_libs_ios_audio: any
  media_kit_libs_macos_audio: any
  just_audio_web: any

  share_plus: ^12.0.1
  url_launcher: ^6.3.2

  dbus: ^0.7.11

  file_picker: ^10.3.3
  flutter_colorpicker: ^1.1.0

  scrollable_positioned_list: ^0.3.8

  timezone: ^0.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^10.0.1
  build_runner: ^2.6.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Roboto Flex
      fonts:
        - asset: assets/fonts/RobotoFlex-VariableFont.ttf
  assets:
    - assets/icons/icon.png
    - assets/icons/app_icon.ico
    - assets/images/checkerboard.png